DROP SCHEMA IF EXISTS MangaApp CASCADE;
CREATE SCHEMA MangaApp;

-- CREATE TYPE reaction AS ENUM ('like', 'dislike');
-- CREATE TYPE user_status AS ENUM ('full_active', 'muted', 'banned');
-- CREATE TYPE manga_status AS ENUM ('approved', 'disapproved');

-- --DROP SCHEMA IF EXISTS MangaApp CASCADE;
-- CREATE SCHEMA MangaApp;

--DROP TABLE MangaApp.USERS;
CREATE TABLE USERS
(
    id       bigint              NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nickname VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL,
    email    VARCHAR(255) UNIQUE NOT NULL,
    image    bytea,
    updated  timestamp DEFAULT NULL,
    PRIMARY KEY (id)
);

--DROP TABLE MangaApp.ROLE;
CREATE TABLE ROLES
(
    id   smallint     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) not null,
    PRIMARY KEY (id)
);

--DROP TABLE MangaApp.USER_ROLE;
CREATE TABLE USERS_ROLES
(
    user_id bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_id smallint NOT NULL,
    CONSTRAINT pk_UserRole PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES ROLES (id) ON DELETE CASCADE
);
--DROP TABLE MangaApp.CREATOR;
CREATE TABLE CREATOR
(
    id          int CHECK (id > 0) NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255)       NOT NULL,
    secondary_names        VARCHAR(255)    ,
    description varchar(1000) DEFAULT '',
    PRIMARY KEY (id)
);

CREATE TABLE MANGA
(
    id                     int          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name             VARCHAR(255) NOT NULL,
    alternative_names VARCHAR(255)          DEFAULT NULL,
    author_id              int          NOT NULL,
    artist_id              int          NOT NULL,
    release_year           smallint              DEFAULT 1722,
    translator_id          int          NOT NULL,
    add_datetime           timestamp    NOT NULL DEFAULT NOW(),
    update_datetime        timestamp    NOT NULL DEFAULT NOW(),
    approval_datetime      timestamp             DEFAULT NULL,
    preview_image_path     VARCHAR(255) NOT NULL,
    is_approved            boolean      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES MangaApp.CREATOR (id),
    FOREIGN KEY (artist_id) REFERENCES MangaApp.CREATOR (id),
    FOREIGN KEY (translator_id) REFERENCES MangaApp.USERS (id)
);

--DROP TABLE MangaApp.MANGA_CHAPTER;
CREATE TABLE MANGA_CHAPTER
(
    id                bigint CHECK (id > 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chapter_name      VARCHAR(255)                                           NOT NULL,
    related_manga_id  int                                                    NOT NULL,
    number_of_chapter smallint CHECK (number_of_chapter > 0)                 NOT NULL,
    chapter_path      varchar(255)                                           NOT NULL,
    add_datetime      timestamp                                              NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (related_manga_id) REFERENCES MangaApp.MANGA (id) ON DELETE CASCADE
);