DROP SCHEMA IF EXISTS MangaApp CASCADE;
CREATE SCHEMA MangaApp;

-- CREATE TYPE reaction AS ENUM ('like', 'dislike');
-- CREATE TYPE user_status AS ENUM ('full_active', 'muted', 'banned');
-- CREATE TYPE manga_status AS ENUM ('approved', 'disapproved');

-- --DROP SCHEMA IF EXISTS MangaApp CASCADE;
-- CREATE SCHEMA MangaApp;

--DROP TABLE MangaApp.USERS;
CREATE TABLE USERS
(
    id       bigint              NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nickname VARCHAR(255) UNIQUE,
    password VARCHAR(255)        NOT NULL,
    email    VARCHAR(255) UNIQUE NOT NULL,
    image    bytea,
    updated  timestamp DEFAULT NULL,
    PRIMARY KEY (id)
);

--DROP TABLE MangaApp.ROLES;
CREATE TABLE ROLES
(
    id   smallint     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) not null,
    PRIMARY KEY (id)
);

--DROP TABLE MangaApp.USER_ROLES;
CREATE TABLE USERS_ROLES
(
    user_id bigint   NOT NULL,
    role_id smallint NOT NULL,
    CONSTRAINT pk_UsersRoles PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES ROLES (id) ON DELETE CASCADE
);
--DROP TABLE MangaApp.CREATORS;
CREATE TABLE CREATORS
(
    id          int CHECK (id > 0) NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255)       NOT NULL,
    secondary_names        VARCHAR(255)    ,
    description varchar(1000) DEFAULT '',
    PRIMARY KEY (id)
);

CREATE TABLE GROUPS
(
    id         bigint CHECK ( id > 0 ) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_name VARCHAR(255) NOT NULL,
    link1      VARCHAR(255) DEFAULT NULL,
    link2      VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE USERS_GROUPS
(
    user_id bigint   NOT NULL,
    group_id bigint NOT NULL,
    CONSTRAINT pk_UsersGroups PRIMARY KEY (user_id, group_id),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES GROUPS (id) ON DELETE CASCADE
);

--DROP TABLE MangaApp.MANGAS;
CREATE TABLE MANGAS
(
    id                     int          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name             VARCHAR(255) NOT NULL,
    alternative_names VARCHAR(255)          DEFAULT NULL,
    author_id              int          NOT NULL,
    artist_id              int          NOT NULL,
    release_year           smallint              DEFAULT 1722,
    description VARCHAR(255),
    group_id          bigint          NOT NULL,
    add_datetime           timestamp    NOT NULL DEFAULT NOW(),
    update_datetime        timestamp    NOT NULL DEFAULT NOW(),
    approval_datetime      timestamp             DEFAULT NULL,
    preview_image_path     VARCHAR(255) NOT NULL,
    is_approved            boolean      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES MangaApp.CREATORS (id),
    FOREIGN KEY (artist_id) REFERENCES MangaApp.CREATORS (id),
    FOREIGN KEY (group_id) REFERENCES MangaApp.GROUPS (id)
);

--DROP TABLE MangaApp.MANGA_CHAPTERS;
CREATE TABLE MANGA_CHAPTERS
(
    id                bigint CHECK (id > 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chapter_name      VARCHAR(255)                                           NOT NULL,
    related_manga_id  int                                                    NOT NULL,
    number_of_chapter smallint CHECK (number_of_chapter > 0)                 NOT NULL,
    chapter_path      varchar(255)                                           NOT NULL,
    add_datetime      timestamp                                              NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (related_manga_id) REFERENCES MangaApp.MANGAS (id) ON DELETE CASCADE
);